document.writeln("<OBJECT classid='clsid:A318A9AC-E75F-424C-9364-6B40A848FC6B' width=1 height=1 id=zkonline hspace='0' border='0' align='top' >");
document.writeln("<param name='Visible' value='-1'>");
document.writeln("<param name='AutoScroll' value='0'>");
document.writeln("<param name='AutoSize' value='0'>");
document.writeln("<param name='AxBorderStyle' value='1'>");
document.writeln("<param name='Caption' value='Biokey Online(1:1)'>");
document.writeln("<param name='Color' value='2147483663'>");
document.writeln("<param name='Font' value='MS Sans Serif'>");
document.writeln("<param name='KeyPreview' value='0'>");
document.writeln("<param name='PixelsPerInch' value='96'>");
document.writeln("<param name='PrintScale' value='1'>");
document.writeln("<param name='Scaled' value='-1'>");
document.writeln("<param name='DropTarget' value='0'>");
document.writeln("<param name='HelpFile' value>");
document.writeln("<param name='DoubleBuffered' value='0'>");
document.writeln("<param name='Enabled' value='-1'>");
document.writeln("<param name='Cursor' value='0'>");
document.writeln("<param name='RegisterTemplate' value>");
document.writeln("<param name='VerifyCount' value='3'>");
document.writeln("<param name='VerifyTemplate' value>");
document.writeln("<param name='ParentFont' value='0'>");
document.writeln("<param name='Threshold' value='10'>");
document.writeln("<param name='OneToOneThreshold' value='10'>");
document.writeln("<param name='CheckFinger' value>");
document.writeln("<param name='EnrollCount' value='3'>");
document.writeln("<param name='DefaultRegFinger' value='0'>");
document.writeln("<param name='DefaultWindowClose' value='0'>");
document.writeln("<param name='SetVerHint' value>");
document.writeln("</OBJECT>");
